name: borsh
description: Borsh is an implementation of the Borsh binary serialization format for Dart.
version: 0.0.1
homepage: https://github.com/kecson/borsh.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  convert: ^3.0.1
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.2
  lints: ^1.0.1

